version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: snt-postgres
    restart: always
    environment:
      POSTGRES_USER: snt_user
      POSTGRES_PASSWORD: snt_password
      POSTGRES_DB: snt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

